/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package michaelmartinez_lab6p2;

/**
 *
 * @author Michael Martínez
 */
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.MutableTreeNode;
public class menuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form menuPrincipal
     */
    public menuPrincipal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_crearEquipo = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_paisEquipo = new javax.swing.JTextField();
        tf_nombreEquipo = new javax.swing.JTextField();
        tf_ciudadEquipo = new javax.swing.JTextField();
        tf_estadioEquipo = new javax.swing.JTextField();
        jb_agregarEQUIPO = new javax.swing.JButton();
        jd_agregarJugador = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tf_nombreJugador = new javax.swing.JTextField();
        sp_edad = new javax.swing.JSpinner();
        cb_posicion = new javax.swing.JComboBox<>();
        jb_agregarJugador = new javax.swing.JButton();
        jd_transferencias = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_listaJugadores = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_EQUIPOS = new javax.swing.JTree();
        jb_transferir = new javax.swing.JButton();
        pm_eliminarEquipo = new javax.swing.JPopupMenu();
        jmi_eliminar = new javax.swing.JMenuItem();
        pp_modificarJugador = new javax.swing.JPopupMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jb_crearEquipo = new javax.swing.JButton();
        jb_crearJugador = new javax.swing.JButton();
        jb_transferencias = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("CREAR EQUIPO");

        jLabel4.setText("PAÍS DEL EQUIPO");

        jLabel5.setText("NOMBRE");

        jLabel6.setText("CIUDAD");

        jLabel7.setText("ESTADIO");

        jb_agregarEQUIPO.setText("AGREGAR");
        jb_agregarEQUIPO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregarEQUIPOMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_crearEquipoLayout = new javax.swing.GroupLayout(jd_crearEquipo.getContentPane());
        jd_crearEquipo.getContentPane().setLayout(jd_crearEquipoLayout);
        jd_crearEquipoLayout.setHorizontalGroup(
            jd_crearEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearEquipoLayout.createSequentialGroup()
                .addGroup(jd_crearEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crearEquipoLayout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_crearEquipoLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jd_crearEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(76, 76, 76)
                        .addGroup(jd_crearEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_ciudadEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                            .addComponent(tf_nombreEquipo)
                            .addComponent(tf_paisEquipo)
                            .addComponent(tf_estadioEquipo)))
                    .addGroup(jd_crearEquipoLayout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(jb_agregarEQUIPO, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(246, Short.MAX_VALUE))
        );
        jd_crearEquipoLayout.setVerticalGroup(
            jd_crearEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearEquipoLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jd_crearEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_paisEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jd_crearEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crearEquipoLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel5))
                    .addGroup(jd_crearEquipoLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(tf_nombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jd_crearEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_ciudadEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(28, 28, 28)
                .addGroup(jd_crearEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_estadioEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jb_agregarEQUIPO, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel8.setText("CREAR JUGADORES");

        jLabel9.setText("NOMBRE DE JUGADOR");

        jLabel10.setText("EDAD");

        jLabel11.setText("POSICION");

        sp_edad.setModel(new javax.swing.SpinnerNumberModel(15, 15, 45, 1));

        cb_posicion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Portero", "Defensa", "Medio", "Delantero" }));

        jb_agregarJugador.setText("AGREGAR");
        jb_agregarJugador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregarJugadorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_agregarJugadorLayout = new javax.swing.GroupLayout(jd_agregarJugador.getContentPane());
        jd_agregarJugador.getContentPane().setLayout(jd_agregarJugadorLayout);
        jd_agregarJugadorLayout.setHorizontalGroup(
            jd_agregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarJugadorLayout.createSequentialGroup()
                .addGroup(jd_agregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_agregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jd_agregarJugadorLayout.createSequentialGroup()
                            .addGap(163, 163, 163)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_agregarJugadorLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jd_agregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jd_agregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jd_agregarJugadorLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(91, 91, 91))
                                    .addComponent(jLabel9))
                                .addGroup(jd_agregarJugadorLayout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(67, 67, 67)))
                            .addGap(80, 80, 80)
                            .addGroup(jd_agregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tf_nombreJugador)
                                .addComponent(sp_edad)
                                .addComponent(cb_posicion, 0, 201, Short.MAX_VALUE))))
                    .addGroup(jd_agregarJugadorLayout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(jb_agregarJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        jd_agregarJugadorLayout.setVerticalGroup(
            jd_agregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarJugadorLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jd_agregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_nombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jd_agregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(sp_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jd_agregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cb_posicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(jb_agregarJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel12.setText("TRANSFERENCIAS");

        jLabel13.setText("JUGADORES");

        jLabel14.setText("EQUIPOS");

        jl_listaJugadores.setModel(new DefaultListModel()
        );
        jl_listaJugadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_listaJugadoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jl_listaJugadores);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("EQUIPOS");
        jt_EQUIPOS.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_EQUIPOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_EQUIPOSMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jt_EQUIPOS);

        jb_transferir.setText("TRANFERIR ->");
        jb_transferir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_transferirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_transferenciasLayout = new javax.swing.GroupLayout(jd_transferencias.getContentPane());
        jd_transferencias.getContentPane().setLayout(jd_transferenciasLayout);
        jd_transferenciasLayout.setHorizontalGroup(
            jd_transferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_transferenciasLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jb_transferir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addGroup(jd_transferenciasLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jd_transferenciasLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(118, 118, 118))
        );
        jd_transferenciasLayout.setVerticalGroup(
            jd_transferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_transferenciasLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jd_transferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_transferenciasLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addGroup(jd_transferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(29, 29, 29)
                        .addGroup(jd_transferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(99, 99, 99))
                    .addGroup(jd_transferenciasLayout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jb_transferir)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jmi_eliminar.setText("Eliminar");
        jmi_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_eliminarActionPerformed(evt);
            }
        });
        pm_eliminarEquipo.add(jmi_eliminar);

        jMenuItem4.setText("Modificar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        pp_modificarJugador.add(jMenuItem4);

        jMenuItem5.setText("Eliminar");
        jMenuItem5.setToolTipText("");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        pp_modificarJugador.add(jMenuItem5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        jb_crearEquipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar.png"))); // NOI18N
        jb_crearEquipo.setText("CREAR EQUIPO");
        jb_crearEquipo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_crearEquipo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jb_crearEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_crearEquipoActionPerformed(evt);
            }
        });
        jToolBar1.add(jb_crearEquipo);

        jb_crearJugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificar.png"))); // NOI18N
        jb_crearJugador.setText("CREAR JUGADOR");
        jb_crearJugador.setFocusable(false);
        jb_crearJugador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_crearJugador.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jb_crearJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_crearJugadorActionPerformed(evt);
            }
        });
        jToolBar1.add(jb_crearJugador);

        jb_transferencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/listar.png"))); // NOI18N
        jb_transferencias.setText("TRANSFERENCIAS");
        jb_transferencias.setFocusable(false);
        jb_transferencias.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_transferencias.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jb_transferencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_transferenciasActionPerformed(evt);
            }
        });
        jToolBar1.add(jb_transferencias);

        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("BIENVENIDO A BOROA LEAGUE FANTASY");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gato.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        jMenu1.setText("OPCIONES");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar.png"))); // NOI18N
        jMenuItem1.setText("CREAR EQUIPO");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificar.png"))); // NOI18N
        jMenuItem2.setText("CREAR JUGADOR");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/listar.png"))); // NOI18N
        jMenuItem3.setText("TRANFERENCIAS");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("AYUDA");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        transferencias();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        crearJugador();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jb_crearEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_crearEquipoActionPerformed
        // TODO add your handling code here:
        crearEquipo();
    }//GEN-LAST:event_jb_crearEquipoActionPerformed

    private void jb_crearJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_crearJugadorActionPerformed
        // TODO add your handling code here:
        crearJugador();
    }//GEN-LAST:event_jb_crearJugadorActionPerformed

    private void jb_transferenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_transferenciasActionPerformed
        // TODO add your handling code here:
        transferencias();
    }//GEN-LAST:event_jb_transferenciasActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        crearEquipo();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jb_agregarEQUIPOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregarEQUIPOMouseClicked
        // TODO add your handling code here:
        DefaultTreeModel modeloArbol=(DefaultTreeModel)jt_EQUIPOS.getModel();
        DefaultMutableTreeNode raiz=(DefaultMutableTreeNode)modeloArbol.getRoot();
        
        String nombre,pais,ciudad,estadio;
        nombre=tf_nombreEquipo.getText();
        pais=tf_paisEquipo.getText();
        ciudad=tf_ciudadEquipo.getText();
        estadio=tf_estadioEquipo.getText();
        int contador = -1;  
        if (tf_nombreEquipo.getText().equals("")||
                tf_paisEquipo.getText().equals("")||
                tf_ciudadEquipo.getText().equals("")||
                tf_estadioEquipo.getText().equals("")) {
            JOptionPane.showMessageDialog(jd_crearEquipo, "Hay un campo vacío");
        }else {
            for (int i = 0; i < raiz.getChildCount(); i++) {
                if (raiz.getChildAt(i).toString().equals(pais)) {
                    DefaultMutableTreeNode nodoHijo = new DefaultMutableTreeNode(new equipo(nombre, pais, ciudad, estadio));
                    ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(nodoHijo);
                    
                    JOptionPane.showMessageDialog(jd_crearEquipo, "EQUIPO AGREGADO CON ÉXITO");
                    contador = 1;
                }
            }

            if (contador == -1) {
                equipo nuevoEquipo = new equipo(nombre, pais, ciudad, estadio);
                DefaultMutableTreeNode nuevoPais = new DefaultMutableTreeNode((String)nuevoEquipo.getPais());
                DefaultMutableTreeNode nodoHijo2 = new DefaultMutableTreeNode(nuevoEquipo);
                nuevoPais.add(nodoHijo2);
                raiz.add(nuevoPais);
                JOptionPane.showMessageDialog(jd_crearEquipo, "EQUIPO AGREGADO CON ÉXITO");
            }
            tf_nombreEquipo.setText("");
            tf_paisEquipo.setText("");
            tf_ciudadEquipo.setText("");
            tf_estadioEquipo.setText("");
            modeloArbol.reload();
        }
        
  
    }//GEN-LAST:event_jb_agregarEQUIPOMouseClicked

    private void jt_EQUIPOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_EQUIPOSMouseClicked
        // TODO add your handling code here:
//        DefaultTreeModel modeloArbol=(DefaultTreeModel)jt_EQUIPOS.getModel();
//        DefaultMutableTreeNode raiz=(DefaultMutableTreeNode)modeloArbol.getRoot();
        
//        for (int i = 0; i < raiz.getChildCount(); i++) {
//            if (raiz.getChildAt(i)) {
//                
//            }
//        }
        if (evt.isMetaDown()) {
            DefaultTreeModel modeloArbol = (DefaultTreeModel) jt_EQUIPOS.getModel();
            Object v = jt_EQUIPOS.getSelectionPath().getLastPathComponent();
            nodo_seleccionado = (DefaultMutableTreeNode) v;
            if (nodo_seleccionado.getUserObject() instanceof equipo) {
                pm_eliminarEquipo.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
       
    }//GEN-LAST:event_jt_EQUIPOSMouseClicked

    private void jmi_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_eliminarActionPerformed
        // TODO add your handling code here:
        DefaultTreeModel modeloArbol=(DefaultTreeModel)jt_EQUIPOS.getModel();
        modeloArbol.removeNodeFromParent(nodo_seleccionado);
        JOptionPane.showMessageDialog(jd_transferencias, "Equipo eliminado");
        
    }//GEN-LAST:event_jmi_eliminarActionPerformed

    private void jb_agregarJugadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregarJugadorMouseClicked
        // TODO add your handling code here:
        DefaultListModel lista=(DefaultListModel)jl_listaJugadores.getModel();
        String nombre,posicion,edad;
        nombre=tf_nombreJugador.getText();
        posicion=(String)cb_posicion.getSelectedItem();
        edad=String.valueOf(sp_edad.getValue());
        if (nombre.equals("")||posicion.equals("")||edad.equals("")) {
            JOptionPane.showMessageDialog(jd_agregarJugador, "Hay un campo vacío");
        }else{
            lista.addElement(new jugador(nombre, posicion, edad));
            jl_listaJugadores.setModel(lista);
            tf_nombreJugador.setText("");
            cb_posicion.setSelectedIndex(0);
            sp_edad.setValue(15);
            JOptionPane.showMessageDialog(jd_agregarJugador, "Jugador agregado");
        }
        
    }//GEN-LAST:event_jb_agregarJugadorMouseClicked

    private void jl_listaJugadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_listaJugadoresMouseClicked
        // TODO add your handling code here:
        DefaultListModel modeloLista=(DefaultListModel)jl_listaJugadores.getModel();
        
        if (evt.isMetaDown()) {
            if (jl_listaJugadores.getSelectedIndex()>=0) {
                pp_modificarJugador.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_jl_listaJugadoresMouseClicked

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        DefaultListModel modeloLista=(DefaultListModel)jl_listaJugadores.getModel();
        String nombre=JOptionPane.showInputDialog(jd_transferencias,"Ingrese el nuevo nombre");
        int contador=0;
        for (int i = 0; i < nombre.length(); i++) {
            if (nombre.charAt(i)>=48 && nombre.charAt(i)<=57) {
                contador++;
            }
        }
        
        if (contador==0) {
            String posicion = JOptionPane.showInputDialog(jd_transferencias, "Ingrese la nueva posicion");
            String edad = JOptionPane.showInputDialog(jd_transferencias, "Ingrese la nueva edad");
            int contador2=0;
            for (int i = 0; i < edad.length(); i++) {
                if (edad.charAt(i) >= 65 && edad.charAt(i) <= 90) {
                    contador2++;
                } else if (edad.charAt(i) >= 97 && edad.charAt(i) <= 122) {
                    contador2++;
                }
            }
            if (contador2==0) {
                Object x = modeloLista.getElementAt(jl_listaJugadores.getSelectedIndex());
                jugador jugador = (jugador) x;
                jugador.setEdad(edad);
                jugador.setNombre(nombre);
                jugador.setPosicion(posicion);
                 JOptionPane.showMessageDialog(jd_transferencias, "Jugador modificado con éxito");
            }else{
                 JOptionPane.showMessageDialog(rootPane, "No se permiten numeros");
            }
            
        }else{
             JOptionPane.showMessageDialog(rootPane, "No se permiten numeros");
        }
       
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        DefaultListModel modeloLista=(DefaultListModel)jl_listaJugadores.getModel();
        DefaultTreeModel modeloArbol=(DefaultTreeModel)jt_EQUIPOS.getModel();
        DefaultMutableTreeNode raiz=(DefaultMutableTreeNode)modeloArbol.getRoot();
       
        Object x = modeloLista.getElementAt(jl_listaJugadores.getSelectedIndex());
//        DefaultMutableTreeNode enArbol=(DefaultMutableTreeNode)x;
//        modeloArbol.removeNodeFromParent(enArbol);
//intenté eliminarlo del arbol con varios for, pero no pude
        
        modeloLista.removeElement(x);
        JOptionPane.showMessageDialog(jd_transferencias, "Jugador eliminado");
        jl_listaJugadores.setModel(modeloLista);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jb_transferirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_transferirMouseClicked
        // TODO add your handling code here:
        DefaultListModel modeloLista=(DefaultListModel)jl_listaJugadores.getModel();
        DefaultTreeModel modeloArbol=(DefaultTreeModel)jt_EQUIPOS.getModel();
        DefaultMutableTreeNode raiz=(DefaultMutableTreeNode)modeloArbol.getRoot();
       
        Object x = modeloLista.getElementAt(jl_listaJugadores.getSelectedIndex());
        jugador jugadorSeleccionado = (jugador) x;
        
        Object v = jt_EQUIPOS.getSelectionPath().getLastPathComponent();
            nodo_seleccionado = (DefaultMutableTreeNode) v;
        
            
        String nombreJugador=jugadorSeleccionado.nombre;
        String edadJugador=jugadorSeleccionado.edad;
        String posicionJugador=jugadorSeleccionado.posicion;
        
        String nombre=((equipo)nodo_seleccionado.getUserObject()).getNombre();
        String pais=((equipo)nodo_seleccionado.getUserObject()).getPais();
        String ciudad=((equipo)nodo_seleccionado.getUserObject()).getCiudad();
        String estadio=((equipo)nodo_seleccionado.getUserObject()).getEstadio();
        if (jl_listaJugadores.getSelectedIndex() >= 0) {
            if ((nodo_seleccionado.getUserObject())instanceof equipo) {
                int contador=-1;
                for (int i = 0; i < nodo_seleccionado.getChildCount(); i++) {
                    if (posicionJugador.equalsIgnoreCase(nodo_seleccionado.getChildAt(i).toString())) {
                        DefaultMutableTreeNode nuevaJugador = new DefaultMutableTreeNode(jugadorSeleccionado);
                        ((DefaultMutableTreeNode)nodo_seleccionado.getChildAt(i)).add(nuevaJugador);
                        contador=1;
                    }
                }
                if (contador==-1) {
                    DefaultMutableTreeNode nuevaPosicion=new DefaultMutableTreeNode((String)jugadorSeleccionado.getPosicion());
                    DefaultMutableTreeNode nuevoJugador=new DefaultMutableTreeNode(jugadorSeleccionado);
                    nuevaPosicion.add(nuevoJugador);
                    nodo_seleccionado.add(nuevaPosicion);
                }
                JOptionPane.showMessageDialog(jd_transferencias, "Jugador transferido");
                modeloArbol.reload();
            }

//            int contador=-1;
//            for (int i = 0; i < raiz.getChildCount(); i++) {
//                if (raiz.getChildAt(i).toString().equals(pais)) {
//                    DefaultMutableTreeNode nodoHijo = new DefaultMutableTreeNode(new equipo(nombre, pais, ciudad, estadio));
//                    ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(nodoHijo);
//                    
//                    JOptionPane.showMessageDialog(jd_crearEquipo, "EQUIPO AGREGADO CON ÉXITO");
//                    contador = 1;
//                }
//            }
            
//            equipo nuevoEquipo = new equipo(nombre, pais, ciudad, estadio);
//            DefaultMutableTreeNode nuevoPais = new DefaultMutableTreeNode((String) nuevoEquipo.getPais());
//            DefaultMutableTreeNode nodoHijo2 = new DefaultMutableTreeNode(nuevoEquipo);
//            nuevoPais.add(nodoHijo2);
//            raiz.add(nuevoPais);

      }
    }//GEN-LAST:event_jb_transferirMouseClicked

    /**
     * @param args the command line arguments
     */
    private void crearJugador(){
        jd_agregarJugador.pack();//hacer mas grande
        jd_agregarJugador.setLocationRelativeTo(this);//ubicacion con respecto al padre
        jd_agregarJugador.setModal(true);//bloquear las otras ventanas
        jd_agregarJugador.setVisible(true);//mostrar dialog
    }
    private void transferencias(){
        jd_transferencias.pack();//hacer mas grande
        jd_transferencias.setLocationRelativeTo(this);//ubicacion con respecto al padre
        jd_transferencias.setModal(true);//bloquear las otras ventanas
        jd_transferencias.setVisible(true);//mostrar dialog
    }
    private void crearEquipo(){
        jd_crearEquipo.pack();//hacer mas grande
        jd_crearEquipo.setLocationRelativeTo(this);//ubicacion con respecto al padre
        jd_crearEquipo.setModal(true);//bloquear las otras ventanas
        jd_crearEquipo.setVisible(true);//mostrar dialog
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuPrincipal().setVisible(true);
            }
        });
    }
DefaultMutableTreeNode nodo_seleccionado;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_posicion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton jb_agregarEQUIPO;
    private javax.swing.JButton jb_agregarJugador;
    private javax.swing.JButton jb_crearEquipo;
    private javax.swing.JButton jb_crearJugador;
    private javax.swing.JButton jb_transferencias;
    private javax.swing.JButton jb_transferir;
    private javax.swing.JDialog jd_agregarJugador;
    private javax.swing.JDialog jd_crearEquipo;
    private javax.swing.JDialog jd_transferencias;
    private javax.swing.JList<String> jl_listaJugadores;
    private javax.swing.JMenuItem jmi_eliminar;
    private javax.swing.JTree jt_EQUIPOS;
    private javax.swing.JPopupMenu pm_eliminarEquipo;
    private javax.swing.JPopupMenu pp_modificarJugador;
    private javax.swing.JSpinner sp_edad;
    private javax.swing.JTextField tf_ciudadEquipo;
    private javax.swing.JTextField tf_estadioEquipo;
    private javax.swing.JTextField tf_nombreEquipo;
    private javax.swing.JTextField tf_nombreJugador;
    private javax.swing.JTextField tf_paisEquipo;
    // End of variables declaration//GEN-END:variables
}
